#!/usr/bin/env python

import os
import sys
import shutil

# append project directory to path so predict.py can be imported
# sys.path.append('.')
# from predict import MODEL_NAME, MODEL_CACHE, CONTROL_CACHE

# Clone ComfyUI repo
os.system("git clone https://github.com/comfyanonymous/ComfyUI.git")
